# Generated by Django 4.1.13 on 2024-03-21 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pdf_Extracter_app', '0003_uploaddata_submitdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitData',
            new_name='SubmitUserData',
        ),
        migrations.CreateModel(
            name='UploadUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=50, null=True)),
                ('agent', models.CharField(blank=True, max_length=50, null=True)),
                ('custom_file', models.CharField(blank=True, max_length=50, null=True)),
                ('dr_file', models.CharField(blank=True, max_length=50, null=True)),
                ('excel_file', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
